spring.application.name=question-service
spring.application.name=quizapp

spring.datasource.url=jdbc:postgresql://localhost:5433/questiondb
spring.datasource.username=postgres
spring.datasource.password=admin@123
spring.jpa.hibernate.ddl-auto=create
